name: Copy File

on: [push]

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy File
      run: |
        # Use the 'cp' command to copy the contents of source.txt into destination.txt
        cp index.html index2.html
